"""Build and verify a publisher-owned external corpus without vendoring it."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Sequence


def _run(
    command: list[str], *, cwd: Path, environment=None
) -> subprocess.CompletedProcess:
    return subprocess.run(
        command,
        cwd=cwd,
        env=environment,
        capture_output=True,
        text=True,
        check=False,
    )


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _source_hashes(content_root: Path) -> dict[str, str]:
    return {
        path.relative_to(content_root).as_posix(): _sha256(path)
        for pattern in ("*.ipynb", "*.nbdata")
        for path in sorted(content_root.glob(pattern))
    }


def _write_config(path: Path, site_root: Path) -> None:
    path.write_text(
        f'''"""Ephemeral external-corpus configuration generated by PLUGIN-003."""
from pathlib import Path
import runpy

SITE_ROOT = Path({str(site_root)!r})
globals().update(runpy.run_path(str(SITE_ROOT / "publishconf.py")))
PATH = str(SITE_ROOT / "content")
THEME = str(SITE_ROOT / "theme")
PLUGIN_PATHS = [str(SITE_ROOT / "plugins")]
PLUGINS = [
    plugin for plugin in PLUGINS
    if plugin not in ("ipynb.markup", "pelican.plugins.ipynb_reader")
] + ["pelican.plugins.ipynb_reader"]
''',
        encoding="utf-8",
    )


def _write_instrumentation(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    (path / "sitecustomize.py").write_text(
        '''"""Process-local no-execution observations for one Pelican subprocess."""
import atexit
import json
import os
import socket
from pathlib import Path

from jupyter_client import KernelManager
from nbclient import NotebookClient

observations = {"client_executes": 0, "kernel_starts": 0, "network_connects": 0}

def blocked_kernel(*args, **kwargs):
    observations["kernel_starts"] += 1
    raise AssertionError("external build attempted to start a kernel")

def blocked_execute(*args, **kwargs):
    observations["client_executes"] += 1
    raise AssertionError("external build attempted to execute a notebook")

original_connect = socket.socket.connect
def observed_connect(instance, address):
    if instance.family in (socket.AF_INET, socket.AF_INET6):
        observations["network_connects"] += 1
        raise AssertionError("external build attempted a network connection")
    return original_connect(instance, address)

KernelManager.start_kernel = blocked_kernel
NotebookClient.execute = blocked_execute
socket.socket.connect = observed_connect

@atexit.register
def record():
    Path(os.environ["PLUGIN003_OBSERVATIONS"]).write_text(
        json.dumps(observations, sort_keys=True) + "\\n", encoding="utf-8"
    )
''',
        encoding="utf-8",
    )


def _validate_build_log(log: str, expected_articles: int) -> dict[str, int]:
    processed = re.search(r"Done: Processed (\d+) articles", log)
    if not processed or int(processed.group(1)) != expected_articles:
        raise RuntimeError(
            f"Pelican did not report exactly {expected_articles} processed articles"
        )
    missing_alt = [
        int(value)
        for value in re.findall(
            r"WARNING\s+Alternative text is missing on (\d+) image\(s\)\.", log
        )
    ]
    empty_alt = len(re.findall(r"WARNING\s+Empty alt attribute for image", log))
    warning_tokens = len(re.findall(r"\bWARNING\b", log))
    if warning_tokens != len(missing_alt) + empty_alt:
        raise RuntimeError(
            "external build emitted a warning outside the narrow alt ledger"
        )
    return {
        "empty_alt": empty_alt,
        "nbconvert_missing_alt": sum(missing_alt),
        "warning_records": warning_tokens,
    }


def _gate_command(args, output: Path, evidence: Path) -> list[str]:
    return [
        args.python,
        "-m",
        "pelican.plugins.ipynb_reader.publication",
        "--expected-manifest",
        str(args.expected_manifest),
        "--baseline-metadata",
        str(args.baseline_metadata),
        "--content-root",
        str(args.site_root / "content"),
        "--output-root",
        str(output),
        "--external-commit",
        args.external_commit,
        "--expected-articles",
        str(args.expected_articles),
        "--expected-notebooks",
        str(args.expected_notebooks),
        "--expected-missing-alt",
        str(args.expected_missing_alt),
        "--expected-empty-alt",
        str(args.expected_empty_alt),
        "--timezone",
        args.timezone,
        "--evidence-out",
        str(evidence),
    ]


def _first_notebook_route(expected_manifest: Path) -> str:
    with expected_manifest.open(encoding="utf-8", newline="") as stream:
        for row in csv.DictReader(stream, delimiter="\t"):
            if row["source"].casefold().endswith(".ipynb"):
                return row["route"]
    raise RuntimeError("expected manifest contains no notebook route")


def _metadata_observations(evidence: dict, owner: str) -> dict:
    notebooks = [
        record for record in evidence["records"] if record["source_kind"] == "notebook"
    ]
    return {
        "inventory_reader_title_mismatches": [
            record["source"]
            for record in notebooks
            if record["publisher_target"]["route_inventory_title"]
            != record["metadata"]["title"]
        ],
        "owner": owner,
        "reader_language_absent": [
            record["source"]
            for record in notebooks
            if record["metadata"]["language"] is None
        ],
        "rendered_language_target_mismatches": [
            record["source"]
            for record in notebooks
            if record["rendered_observation"]["html_lang"]
            != record["publisher_target"]["language"]
        ],
    }


def run(args) -> dict:
    site_root = args.site_root.resolve()
    args.expected_manifest = args.expected_manifest.resolve()
    args.baseline_metadata = args.baseline_metadata.resolve()
    work_root = args.work_root.resolve()
    if work_root.exists():
        shutil.rmtree(work_root)
    work_root.mkdir(parents=True)

    head = _run(["git", "rev-parse", "HEAD"], cwd=site_root)
    status = _run(["git", "status", "--porcelain"], cwd=site_root)
    if head.returncode or head.stdout.strip() != args.external_commit:
        raise RuntimeError("external checkout is not at the required exact commit")
    if status.returncode or status.stdout:
        raise RuntimeError("external checkout must remain clean and read-only")

    config = work_root / "external-pelicanconf.py"
    instrumentation = work_root / "instrumentation"
    _write_config(config, site_root)
    _write_instrumentation(instrumentation)
    before = _source_hashes(site_root / "content")
    marker = work_root / "executed.marker"
    evidence_paths: list[Path] = []
    warning_ledgers: list[dict[str, int]] = []
    observations: list[dict[str, int]] = []

    for number in (1, 2):
        output = work_root / f"output-{number}"
        observation_path = work_root / f"observations-{number}.json"
        environment = {
            **os.environ,
            "PELICAN_IPYNB_SENTINEL_MARKER": str(marker),
            "PLUGIN003_OBSERVATIONS": str(observation_path),
            "PYTHONPATH": str(instrumentation),
        }
        build = _run(
            [
                args.python,
                "-m",
                "pelican",
                str(site_root / "content"),
                "--output",
                str(output),
                "--settings",
                str(config),
                "--delete-output-directory",
                "--fatal",
                "errors",
            ],
            cwd=site_root,
            environment=environment,
        )
        log = build.stdout + build.stderr
        if build.returncode:
            raise RuntimeError(f"external Pelican build {number} failed:\n{log}")
        warning_ledgers.append(_validate_build_log(log, args.expected_articles))
        observed = json.loads(observation_path.read_text(encoding="utf-8"))
        if any(observed.values()):
            raise RuntimeError(f"no-execution observations are not zero: {observed!r}")
        observations.append(observed)

        evidence = work_root / f"evidence-{number}.json"
        gate = _run(_gate_command(args, output, evidence), cwd=work_root)
        if gate.returncode:
            raise RuntimeError(
                f"publication completeness run {number} failed:\n"
                f"{gate.stdout}{gate.stderr}"
            )
        evidence_paths.append(evidence)

    if evidence_paths[0].read_bytes() != evidence_paths[1].read_bytes():
        raise RuntimeError("external machine-readable evidence is not deterministic")
    if warning_ledgers[0] != warning_ledgers[1]:
        raise RuntimeError("external warning ledger is not deterministic")
    if _source_hashes(site_root / "content") != before:
        raise RuntimeError("external source bytes changed during integration")
    if marker.exists():
        raise RuntimeError("external integration created the execution marker")

    negative_output = work_root / "negative-output"
    shutil.copytree(work_root / "output-1", negative_output)
    missing_route = _first_notebook_route(args.expected_manifest)
    (negative_output / missing_route.lstrip("/")).unlink()
    negative_evidence = work_root / "negative-evidence.json"
    negative = _run(
        _gate_command(args, negative_output, negative_evidence), cwd=work_root
    )
    negative_log = negative.stdout + negative.stderr
    required_failure = (
        "publication_verification",
        "missing_expected_route",
        "MissingExpectedRoute",
    )
    if negative.returncode == 0 or not all(
        token in negative_log for token in required_failure
    ):
        raise RuntimeError(
            "negative completeness gate did not return the typed failure"
        )

    gate_evidence = json.loads(evidence_paths[0].read_text(encoding="utf-8"))
    metadata_observations = _metadata_observations(
        gate_evidence, args.metadata_gap_owner
    )
    expected_metadata_gaps = {
        "inventory_reader_title_mismatches": args.expected_title_gaps,
        "reader_language_absent": args.expected_reader_language_absent,
        "rendered_language_target_mismatches": (args.expected_rendered_language_gaps),
    }
    for field, expected_count in expected_metadata_gaps.items():
        actual_count = len(metadata_observations[field])
        if actual_count != expected_count:
            raise RuntimeError(
                f"metadata observation {field} expected {expected_count}, "
                f"observed {actual_count}"
            )
    result = {
        "contract": "pelican-ipynb-external-integration.v1",
        "counts": gate_evidence["counts"],
        "deterministic_evidence_sha256": _sha256(evidence_paths[0]),
        "external_commit": args.external_commit,
        "emitted_build_warning_ledger": warning_ledgers[0],
        "metadata_observations": metadata_observations,
        "negative_gate": {
            "category": "missing_expected_route",
            "exit_code": negative.returncode,
            "route": missing_route,
        },
        "no_execution": {
            "marker_created": False,
            "observations": observations,
            "source_bytes_unchanged": True,
        },
        "output_modes": gate_evidence["output_modes"],
        "publication_records": gate_evidence["records"],
        "warning_ledger": gate_evidence["warning_ledger"],
    }
    args.report_out.parent.mkdir(parents=True, exist_ok=True)
    args.report_out.write_text(
        json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return result


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument("--site-root", type=Path, required=True)
    result.add_argument("--external-commit", required=True)
    result.add_argument("--expected-manifest", type=Path, required=True)
    result.add_argument("--baseline-metadata", type=Path, required=True)
    result.add_argument("--work-root", type=Path, required=True)
    result.add_argument("--report-out", type=Path, required=True)
    result.add_argument("--python", default=sys.executable)
    result.add_argument("--expected-articles", type=int, required=True)
    result.add_argument("--expected-notebooks", type=int, required=True)
    result.add_argument("--expected-missing-alt", type=int, default=0)
    result.add_argument("--expected-empty-alt", type=int, default=0)
    result.add_argument("--expected-title-gaps", type=int, required=True)
    result.add_argument("--expected-reader-language-absent", type=int, required=True)
    result.add_argument("--expected-rendered-language-gaps", type=int, required=True)
    result.add_argument("--metadata-gap-owner", required=True)
    result.add_argument("--timezone", default="UTC")
    return result


def main(argv: Sequence[str] | None = None) -> int:
    args = parser().parse_args(argv)
    try:
        result = run(args)
    except Exception as error:
        print(f"external corpus failed: {error}", file=sys.stderr)
        return 1
    counts = result["counts"]
    print(
        "external corpus passed twice: "
        f"{counts['markdown']} Markdown + {counts['notebooks']} notebooks = "
        f"{counts['articles']} articles; negative gate exit "
        f"{result['negative_gate']['exit_code']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
